version: '3.11'

services:
  db:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./notification_service/.env
    ports:
      - "5432:5432"

  backend_notification:
    build: ./notification_service/notification/
    restart: always
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn setting.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - static_value:/notification/static/
      - media_value:/notification/media/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - db
      - backend_notification

volumes:
  postgres_data:
  static_value:
  media_value: